
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class benzerlikarastirma extends javax.swing.JFrame {

    /**
     * Creates new form benzerlikarastirma
     */
    
    public benzerlikarastirma() {
        initComponents();
       
      
     
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        arama_tablosu = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));

        jTextField1.setBackground(new java.awt.Color(204, 102, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("İŞLEM YAPILACAK SÜTUNU SEÇİN:");

        jTextField2.setBackground(new java.awt.Color(204, 102, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("THREAD SAYISI GİRİN:");

        jTextField3.setBackground(new java.awt.Color(204, 102, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setText("BENZERLİK ORANI GİRİN:");

        jTextField5.setBackground(new java.awt.Color(204, 102, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setText("HANGİ DEĞERLERİ GÖRÜNTÜLEMEK İSTERSİNİZ:");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("LİSTELE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Issue", "Company", "State", "Complaint ID", "Zip Code" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BÜYÜK(>)", "KÜÇÜK(<)", "EŞİT" }));

        arama_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KAYIT 1", "KAYIT 2", "BENZERLİK"
            }
        ));
        jScrollPane1.setViewportView(arama_tablosu);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÇALIŞMA SÜRESİ"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 159, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jComboBox1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int findMatchCount(String[] a, String[] b) {
        List<String> list1 = new ArrayList(Arrays.asList(a));
        List<String> list2 = Arrays.asList(b);
        list1.retainAll(list2);
        return list1.size();
    }
    public void tumislem()
 {  List<WorkerThread> islemler = new ArrayList<>();
      WorkerThread w1=new WorkerThread();
      String count1= jTextField7.getText();
      try{
    
       int count2=Integer.parseInt(count1);
      long sure=w1.kararfonksiyonu(2);
      for ( int i = 0; i <count2; i++){
           WorkerThread w2=new WorkerThread();
        
        islemler.add(w2);
          
        w2.start();
        }

        for(WorkerThread t : islemler){
            try {
                t.join();
            } catch (InterruptedException ex) {
                System.out.println("");
            }
        }
    
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                              
                            model.setColumnCount(count2);
                            
                            Object[] eklenecek = {sure};
                            model.addRow(eklenecek);
      
      

      } catch(NumberFormatException ex){ // handle your exception
          System.out.println("");
}
           
                
                    
                          
                      
      
     
 }
   
        

    public float islemyaptir(String[] a, String[] b) {
        int kontrol = 0;
        if (a.length > b.length) {
            kontrol = 1;
        }

        if (a.length < b.length) {

            kontrol = -1;
        }
        if (a.length == b.length) {

            kontrol = 0;

        }

        float benzerlikorani = 0;
        if (kontrol == 1) {
            int sonuc2 = findMatchCount(a, b);

            //burada a buyuktur b oldugundan anın uzunlugu alınacak
            benzerlikorani = (((float) sonuc2) / ((float) a.length)) * 100;

        }
        if (kontrol == (-1)) {
            int sonuc2 = findMatchCount(a, b);
            //b uzun

            benzerlikorani = (((float) sonuc2) / ((float) b.length)) * 100;

        }
        if (kontrol == 0) {
            int sonuc2 = findMatchCount(a, b);

            benzerlikorani = (((float) sonuc2) / ((float) b.length)) * 100;
        }
        return benzerlikorani;
    }
    public void anafonksiyon()
    {
        
        
          int sutunid=jComboBox1.getSelectedIndex();
            
             if(sutunid!=-1)
             {
            String aranan=jTextField3.getText();
                    
           String karsilastilacakeleman = jTextField8.getText();
           int benzerlikorani = Integer.parseInt(karsilastilacakeleman);
            List<String> rowList = new ArrayList<String>();
            try ( BufferedReader br = new BufferedReader(new FileReader("yazlab21.csv"))) {
                String line;
                while ((line = br.readLine()) != null) {

                    rowList.add(line);
                }
                int count = rowList.size();
                System.out.println(count);
                int i, j,k;
                String[][] matrix = new String[count][6];
                String[] data;

                for (i = 0; i < count; i++) {
                    data = rowList.get(i).split(",");

                    for (j = 0; j < data.length; j++) {

                        matrix[i][j] = data[j];
                    }

                }
                Scanner scan = new Scanner(System.in);
             
                             for (j = 1; j < count; j++) {

                               for (k = count - 1; k > j; k--) {
                               String kelime1= matrix[j][sutunid];
                               String kelime2= matrix[k][sutunid];
                               
                              String arr4[] = kelime1.split(" ");
                             String arr5[] = kelime2.split(" ");
                              
                               
                          float sonuc4 = islemyaptir(arr4, arr5);
                          //buyukluk kucukluk
                           if(jComboBox2.getSelectedIndex()==0)
                          {{
                          if(sonuc4>benzerlikorani)
                          {       tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                                
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc4};
                            model.addRow(eklenecek);
                         }
                        }}
                           if(jComboBox2.getSelectedIndex()==1)
                          {{
                          if(sonuc4<benzerlikorani)
                          {      tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                               
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc4};
                            model.addRow(eklenecek);}
                        }}
                           if(jComboBox2.getSelectedIndex()==2)
                          {{
                          if(sonuc4==benzerlikorani)
                          {       tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                              
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc4};
                            model.addRow(eklenecek);}
                        }}
                           
                           
                           
                           
                           
                    }}}

             catch (Exception e) {
                // Handle any I/O problems
            }}
            


           



        
        
        
        
        
        
        
        
    }
   

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       anafonksiyon();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(benzerlikarastirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(benzerlikarastirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(benzerlikarastirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(benzerlikarastirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
              

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new benzerlikarastirma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable arama_tablosu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
