
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */

public class benzerlikfiltre extends javax.swing.JFrame {
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        arama_tablosu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ÇALIŞMA_SÜRESİ = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setBackground(new java.awt.Color(204, 153, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("%100 BENZER KAYITLARI LİSTELEMEK İÇİN SÜTUN SEÇ:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Issue", "Company", "State", "ZIP code", "Complaint ID" }));

        jTextField2.setBackground(new java.awt.Color(204, 153, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("BENZERLİK ORANINA GÖRE FİLTRELEME YAPACAĞIN SÜTUNU SEÇ:");

        jTextField3.setBackground(new java.awt.Color(204, 153, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setText("BENZERLİK ORANI GİR:");

        jTextField5.setBackground(new java.awt.Color(204, 153, 255));
        jTextField5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setText("EKSTRA OLRAK GÖSTERMEK İSTEĞİNİZ SÜTUNU SEÇİN:");

        arama_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KAYIT 1", "KAYIT 2", "BENZERLİK"
            }
        ));
        jScrollPane1.setViewportView(arama_tablosu);
        if (arama_tablosu.getColumnModel().getColumnCount() > 0) {
            arama_tablosu.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setText("LİSTELE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(204, 153, 255));
        jTextField6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(51, 51, 51));
        jTextField6.setText("BENZERLİK ORANI FİLTRELE:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BÜYÜK DEĞERLER", "KÜÇÜK DEĞERLER", "EŞİT DEĞERLER" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Issue", "Company", "State", "ZIP code", "Complaint ID" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Issue", "Company", "State", "ZIP code", "Complaint ID" }));

        jTextField7.setBackground(new java.awt.Color(204, 153, 255));
        jTextField7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField7.setText("THREAD SAYISI GİR:");

        ÇALIŞMA_SÜRESİ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÇALIŞMA SÜRESİ"
            }
        ));
        jScrollPane3.setViewportView(ÇALIŞMA_SÜRESİ);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(577, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jComboBox3)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField8))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
       
    /**
     * Creates new form benzerlikfiltre
     */
    public benzerlikfiltre() {
        initComponents();

      
    }
    
    
    
  
    
    
    
    
    
    
    public int findMatchCount(String[] a, String[] b) {
        List<String> list1 = new ArrayList(Arrays.asList(a));
        List<String> list2 = Arrays.asList(b);
        list1.retainAll(list2);
        return list1.size();
    }
    
    public void tumislem()
 {  List<WorkerThread> islemler = new ArrayList<>();
      WorkerThread w1=new WorkerThread();
      String count1= jTextField8.getText();
      try{
    
       int count2=Integer.parseInt(count1);
      long sure=w1.kararfonksiyonu(1);
      for ( int i = 0; i <count2; i++){
           WorkerThread w2=new WorkerThread();
        
        islemler.add(w2);
          
        w2.start();
        }

        for(WorkerThread t : islemler){
            try {
                t.join();
            } catch (InterruptedException ex) {
                System.out.println("");
            }
        }
    
          DefaultTableModel model = (DefaultTableModel) ÇALIŞMA_SÜRESİ.getModel();
                              
                            model.setColumnCount(count2);
                            
                            Object[] eklenecek = {sure};
                            model.addRow(eklenecek);
      
      

      } catch(NumberFormatException ex){ // handle your exception
          System.out.println("");
}
           
                
                    
                          
                      
      
     
 }
    
        
 
    public float islemyaptir(String[] a, String[] b) {
        int kontrol = 0;
        if (a.length > b.length) {
            kontrol = 1;
        }

        if (a.length < b.length) {

            kontrol = -1;
        }
        if (a.length == b.length) {

            kontrol = 0;

        }

        float benzerlikorani = 0;
        if (kontrol == 1) {
            int sonuc2 = findMatchCount(a, b);

            //burada a buyuktur b oldugundan anın uzunlugu alınacak
            benzerlikorani = (((float) sonuc2) / ((float) a.length)) * 100;

        }
        if (kontrol == (-1)) {
            int sonuc2 = findMatchCount(a, b);
            //b uzun

            benzerlikorani = (((float) sonuc2) / ((float) b.length)) * 100;

        }
        if (kontrol == 0) {
            int sonuc2 = findMatchCount(a, b);

            benzerlikorani = (((float) sonuc2) / ((float) b.length)) * 100;
        }
        return benzerlikorani;
    }
 

    public void anafonksiyon()
    { 
         int sutunid=jComboBox1.getSelectedIndex();
            
             if(sutunid!=-1)
             {
                 //
                
                 
             String aranan;
            aranan=jTextField3.getText();
                    
           String karsilastilacakeleman = jTextField4.getText();
           int benzerlikorani = Integer.parseInt(karsilastilacakeleman);
            List<String> rowList = new ArrayList<String>();
            try ( BufferedReader br = new BufferedReader(new FileReader("yazlab21.csv"))) {
                String line;
                while ((line = br.readLine()) != null) {

                    rowList.add(line);
                }
                int count = rowList.size();
                System.out.println(count);
                int i, j,k;
                String[][] matrix = new String[count][6];
                String[] data;

                for (i = 0; i < count; i++) {
                    data = rowList.get(i).split(",");

                    for (j = 0; j < data.length; j++) {

                        matrix[i][j] = data[j];
                    }

                }
                Scanner scan = new Scanner(System.in);
             
                             for (j = 1; j < count; j++) {

                               for (k = count - 1; k > j; k--) {
                               String kelime1= matrix[j][sutunid];
                               String kelime2= matrix[k][sutunid];
                               
                              String arr4[] = kelime1.split(" ");
                             String arr5[] = kelime2.split(" ");
                              
                               
                          float sonuc4 = islemyaptir(arr4, arr5);
                          if(sonuc4==100.0)
                              //sutunid2 benzerlik arayacagım
                          {  int sutunid3=jComboBox4.getSelectedIndex();
                             int sutunid2=jComboBox3.getSelectedIndex();
                              if((sutunid!=sutunid2) &&(sutunid2!=sutunid3) &&(sutunid3!=sutunid))
                              {
                                  for (j = 1; j < count; j++) {
                              
                               for (k = count - 1; k > j; k--) {
                                    Object sutunname1=jComboBox3.getSelectedItem();
                                    Object sutunname2=jComboBox4.getSelectedItem();
                               String kelime4 = matrix[j][sutunid2];
                               String kelime5 = matrix[k][sutunid2];
                               String kelime6=matrix[j][sutunid3];
                               String kelime7=matrix[k][sutunid3];
                               
                              String arr6[] = kelime4.split(" ");
                             String arr7[] = kelime5.split(" ");
                               
                          float sonuc5= islemyaptir(arr6, arr7);
                          if(jComboBox2.getSelectedIndex()==0)
                          {{
                          if(sonuc5>benzerlikorani)
                          {      tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                                 model.addColumn(sutunname1+" KAYIT1");
                                 model.addColumn(sutunname1+" KAYIT2");
                                 model.addColumn(sutunname1+" BENZERLİK");
                                 model.addColumn(sutunname2+"EKSTRA KAYIT1");
                                 model.addColumn(sutunname2+"EKSTRA KAYIT2");
                                
                            model.setColumnCount(8);
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc4,kelime4,kelime5,sonuc5,kelime6,kelime7};
                            model.addRow(eklenecek);}}}
                           if(jComboBox2.getSelectedIndex()==1)
                          {{
                          if(sonuc5<benzerlikorani)
                          {     tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                                 model.addColumn(sutunname1+" KAYIT1");
                                 model.addColumn(sutunname1+" KAYIT2");
                                 model.addColumn(sutunname1+" BENZERLİK");
                                 model.addColumn(sutunname2+"EKSTRA KAYIT1");
                                 model.addColumn(sutunname2+"EKSTRA KAYIT2");
                            model.setColumnCount(8);
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc4,kelime4,kelime5,sonuc5,kelime6,kelime7};
                            model.addRow(eklenecek);}}}
                            if(jComboBox2.getSelectedIndex()==2)
                          {{
                          if(sonuc5==benzerlikorani)
                          {      tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                                  model.addColumn(sutunname1+" KAYIT1");
                                 model.addColumn(sutunname1+" KAYIT2");
                                 model.addColumn(sutunname1+" BENZERLİK");
                                 model.addColumn(sutunname2+"EKSTRA KAYIT1");
                                 model.addColumn(sutunname2+"EKSTRA KAYIT2");
                            model.setColumnCount(8);
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc4,kelime4,kelime5,sonuc5,kelime6,kelime7};
                            model.addRow(eklenecek);}}}
                        }
                    }}
                             
                          
                          
                          
                          }
                              }
                              
                              
                              
                              
                              
                              
                              
                              
                          }
                          
                    }

             catch (Exception e) {
                // Handle any I/O problems
            }}
            




    }
 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
          anafonksiyon();
         
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        //</editor-fold>

        /* Create and display the form */
         
          java.awt.EventQueue.invokeLater(new Runnable() {
         @Override
         public void run() {
            new  benzerlikfiltre().setVisible(true);;  // Let the constructor do the job
         }
      });
       
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable arama_tablosu;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable ÇALIŞMA_SÜRESİ;
    // End of variables declaration//GEN-END:variables

}