
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class sutunelemanarama extends javax.swing.JFrame {

    /**
     * Creates new form sutunelemanarama
     */
    public sutunelemanarama() {
        initComponents();
    }
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        arama_tablosu = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setBackground(new java.awt.Color(204, 153, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField1.setText("ARAMA YAPMAK İSTEGİNİZ SÜTUNU SEÇİN:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Issue", "Company", "State", "Complaint Id", "Zip Code" }));

        jTextField2.setBackground(new java.awt.Color(204, 153, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField2.setText("ARADIĞINIZ BİLGİYİ GİRİN:");

        jTextField4.setBackground(new java.awt.Color(204, 153, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField4.setText("THREAD SAYISI GİRİN:");

        arama_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KAYIT 1", "KAYIT 2", "BENZERLİK"
            }
        ));
        jScrollPane1.setViewportView(arama_tablosu);

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("LİSTELE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(204, 153, 255));
        jTextField6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField6.setText("BENZERLİK GÖRMEK İSTEDİĞİNİZ SÜTUNU SEÇİN:");

        jTextField7.setBackground(new java.awt.Color(204, 153, 255));
        jTextField7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField7.setText("GÖRMEK İSTEĞİNİZ SÜTUNLARDAKİ BENZERLİK ORANINI GİRİN:");

        jTextField9.setBackground(new java.awt.Color(204, 153, 255));
        jTextField9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField9.setText("HANGİ DEĞERLERİ GÖRMEK İSTERSİNİZ:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BÜYÜK", "KÜÇÜK", "EŞİT" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product", "Issue", "Company", "State", "Complaint Id", "Zip Code" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÇALIŞMA SÜRESİ"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(jTextField5))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public int findMatchCount(String[] a, String[] b) {
        List<String> list1 = new ArrayList(Arrays.asList(a));
        List<String> list2 = Arrays.asList(b);
        list1.retainAll(list2);
        return list1.size();
    }
  public void tumislem()
 {  List<WorkerThread> islemler = new ArrayList<>();
      WorkerThread w1=new WorkerThread();
      String count1= jTextField5.getText();
      try{
    
       int count2=Integer.parseInt(count1);
      long sure=w1.kararfonksiyonu(3);
      for ( int i = 0; i <count2; i++){
           WorkerThread w2=new WorkerThread();
        
        islemler.add(w2);
          
        w2.start();
        }

        for(WorkerThread t : islemler){
            try {
                t.join();
            } catch (InterruptedException ex) {
                System.out.println("");
            }
        }
    
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                              
                            model.setColumnCount(count2);
                            
                            Object[] eklenecek = {sure};
                            model.addRow(eklenecek);
      
      

      } catch(NumberFormatException ex){ // handle your exception
          System.out.println("");
}
           
                
                    
                          
                      
      
     
 }
 
    public float islemyaptir(String[] a, String[] b) {
        int kontrol = 0;
        if (a.length > b.length) {
            kontrol = 1;
        }

        if (a.length < b.length) {

            kontrol = -1;
        }
        if (a.length == b.length) {

            kontrol = 0;

        }

        float benzerlikorani = 0;
        if (kontrol == 1) {
            int sonuc2 = findMatchCount(a, b);

            //burada a buyuktur b oldugundan anın uzunlugu alınacak
            benzerlikorani = (((float) sonuc2) / ((float) a.length)) * 100;

        }
        if (kontrol == (-1)) {
            int sonuc2 = findMatchCount(a, b);
            //b uzun

            benzerlikorani = (((float) sonuc2) / ((float) b.length)) * 100;

        }
        if (kontrol == 0) {
            int sonuc2 = findMatchCount(a, b);

            benzerlikorani = (((float) sonuc2) / ((float) b.length)) * 100;
        }
        return benzerlikorani;
    }
    public void anafonksiyon()
    {
        
        //PRODUCT SEÇİLİRSE
        int aramasutunu=jComboBox1.getSelectedIndex();
         if (jComboBox1.getSelectedIndex()!=-1){
            String aranan=jTextField3.getText();
                    
           String karsilastilacakeleman = jTextField8.getText();
           int benzerlikorani = Integer.parseInt(karsilastilacakeleman);
            List<String> rowList = new ArrayList<String>();
            try ( BufferedReader br = new BufferedReader(new FileReader("yazlab21.csv"))) {
                String line;
                while ((line = br.readLine()) != null) {

                    rowList.add(line);
                }
                int count = rowList.size();
                System.out.println(count);
                int i, j;
                String[][] matrix = new String[count][6];
                String[] data;

                for (i = 0; i < count; i++) {
                    data = rowList.get(i).split(",");

                    for (j = 0; j < data.length; j++) {

                        matrix[i][j] = data[j];
                    }

                }

                Scanner scan = new Scanner(System.in);
                
                int goruntuleneceksutun=jComboBox3.getSelectedIndex();
                if(goruntuleneceksutun!=-1)
                {
              int k;
                for (j = 1; j < count; j++) {

                    for ( k = count - 1; k > j; k--) {
                        String kelime1 = matrix[j][aramasutunu];
                        String kelime2 = matrix[k][aramasutunu];

                        String arr1[] = kelime1.split(" ");
                        String arr2[] = kelime2.split(" ");
                        String arr3[] =aranan.split(" ");
                          float sonuc2 = islemyaptir(arr1, arr3);
                          float sonuc3 = islemyaptir(arr2, arr3);
                        
                        float sonuc = islemyaptir(arr1, arr2);
                        if (sonuc2==100.0 && sonuc3==100.0) {
                             for (j = 1; j < count; j++) {

                               for (k = count - 1; k > j; k--) {
                               String kelime4 = matrix[j][goruntuleneceksutun];
                               String kelime5 = matrix[k][goruntuleneceksutun];
                               Object tablo1=jComboBox3.getSelectedItem();
                              String arr4[] = kelime4.split(" ");
                             String arr5[] = kelime5.split(" ");
                              
                               
                          float sonuc4 = islemyaptir(arr4, arr5);
                          //buyukluk kucukluk
                           if(jComboBox2.getSelectedIndex()==0)
                          {{
                          if(sonuc4>benzerlikorani)
                          {    tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                                 
                               model.addColumn(tablo1);
                                 model.addColumn(tablo1);
                                 model.addColumn(" BENZERLIK");
                            model.setColumnCount(6);
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc2,kelime4,kelime5,sonuc4};
                            model.addRow(eklenecek);}
                        }}
                           if(jComboBox2.getSelectedIndex()==1)
                          {{
                          if(sonuc4<benzerlikorani)
                          {     tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                            model.addColumn(tablo1);
                                 model.addColumn(tablo1);
                                 model.addColumn(" BENZERLIK");
                                
                            model.setColumnCount(6);
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc2,kelime4,kelime5,sonuc4};
                            model.addRow(eklenecek);}
                        }}
                           if(jComboBox2.getSelectedIndex()==2)
                          {{
                          if(sonuc4==benzerlikorani)
                          {    tumislem();
                               DefaultTableModel model = (DefaultTableModel) arama_tablosu.getModel();
                                model.addColumn(tablo1);
                                 model.addColumn(tablo1);
                                 model.addColumn(" BENZERLIK");
                            model.setColumnCount(6);
                            
                            Object[] eklenecek = {kelime1, kelime2, sonuc2,kelime4,kelime5,sonuc4};
                            model.addRow(eklenecek);}
                        }}
                           
                           
                           
                           
                           
                    }

                    
               

                        }}}}}
              
                
            }
             catch (Exception e) {
                // Handle any I/O problems
            }
        }}
        
        
        
        
        
        
        
        
   
    


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        
        /*  String count1= jTextField5.getText();
      
       int count2=Integer.parseInt(count1);
       int i;
       
         for(i=0;i<count2;i++){
           Thread t = new Thread()
           {  long baslangiczamani=System.currentTimeMillis();
               @Override
               public void run() {  // override the run() to specify the running behavior*/
                  anafonksiyon();
                    
                  
                      
             /* long calismasuresi = System.currentTimeMillis()-baslangiczamani;
               double sure4=calismasuresi*1.66666667*0.00000000001;
                  ArrayList<Long> arrList = new ArrayList<Long>();
                
                      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                              
                            model.setColumnCount(count2);
                            
                            Object[] eklenecek = {sure4};
                            model.addRow(eklenecek);
                          
                      
           }}
         
        
         
                
                 
                
               
             
            ;
           
            t.start();  // call back run()
         
         }*/
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        
        
        
        
        
        

        
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sutunelemanarama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sutunelemanarama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sutunelemanarama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sutunelemanarama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sutunelemanarama().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable arama_tablosu;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
        }
